### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by Valkhan** [MicrosoftDocs/azure-docs.pt-br#242]
There is no App Configuration menu, only Configuration that does not have PHP stack anymore.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5e564777-8d59-9065-6f0d-d8ea3fc6ee62
* Version Independent ID: ec93756c-4d7f-efc8-a8ca-9b87d1be8ac3
* Content: [Configurar o tempo de execução de PHP – Serviço de Aplicativo do Azure](https://docs.microsoft.com/pt-br/azure/app-service/web-sites-php-configure#feedback)
* Content Source: [articles/app-service/web-sites-php-configure.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/app-service/web-sites-php-configure.md)
* Service: **app-service**
* GitHub Login: @msangapu
* Microsoft Alias: **msangapu**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #29902](https://github.com/MicrosoftDocs/azure-docs/issues/29902) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Valkhan

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/29902

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
