### ISSUE TITLE
[ADD AZURE REPLICA] DONT APPEARS

### ISSUE THREAD

**Issue by mmgil** [MicrosoftDocs/azure-docs.pt-br#409]
I'm using SQL Server 2017 and "Add Azure Replica" dont appears in my wizard...

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 0e8e9cf2-a018-4898-cee7-0943804bb4fa
* Version Independent ID: 571a7f39-3274-7ba3-dfc6-89f0d50ccef5
* Content: [Estender Grupos de Disponibilidade AlwaysOn locais para o Azure](https://docs.microsoft.com/pt-br/azure/virtual-machines/windows/sqlclassic/virtual-machines-windows-classic-sql-onprem-availability#feedback)
* Content Source: [articles/virtual-machines/windows/sqlclassic/virtual-machines-windows-classic-sql-onprem-availability.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/virtual-machines/windows/sqlclassic/virtual-machines-windows-classic-sql-onprem-availability.md)
* Service: **virtual-machines-sql**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #33854](https://github.com/MicrosoftDocs/azure-docs/issues/33854) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @mmgil 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/33854

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
