### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by biarocha** [MicrosoftDocs/azure-docs.pt-br#421]
The link from " configuration guide for ArcSight SmartConnector for Azure Monitor Event Hub." is broken.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: bdb257b2-dce3-fe06-c84d-4784fc701f5b
* Version Independent ID: 9553d0d3-ebd6-1d99-e483-6ec937c274bf
* Content: [Como integrar os logs do Azure Active Directory ao ArcSight usando o Azure Monitor](https://docs.microsoft.com/pt-br/azure/active-directory/reports-monitoring/howto-integrate-activity-logs-with-arcsight#feedback)
* Content Source: [articles/active-directory/reports-monitoring/howto-integrate-activity-logs-with-arcsight.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/active-directory/reports-monitoring/howto-integrate-activity-logs-with-arcsight.md)
* Service: **active-directory**
* Sub-service: **report-monitor**
* GitHub Login: @MarkusVi
* Microsoft Alias: **markvi**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #34203](https://github.com/MicrosoftDocs/azure-docs/issues/34203) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @biarocha

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/34203

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
