### ISSUE TITLE
Wronk link in "Custom error pages"

### ISSUE THREAD

**Issue by hugbro** [MicrosoftDocs/azure-docs.pt-br#465]
As stated above, in section Custom Error Pages, the link that redirects for more information is wrong, redirecting for Rewrite HTTP Headers.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 68677bfe-232b-3f9f-5473-005098e7231d
* Version Independent ID: ab0e9bbf-b9cd-acdc-054d-ca64bf6700bb
* Content: [O que é o Gateway de Aplicativo do Azure](https://docs.microsoft.com/pt-br/azure/application-gateway/overview#feedback)
* Content Source: [articles/application-gateway/overview.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/application-gateway/overview.md)
* Service: **application-gateway**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by srvbpigh** [comment]
Hello, @hugbro
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #35955](https://github.com/MicrosoftDocs/azure-docs/issues/35955) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @hugbro

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/35955

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
