### ISSUE TITLE
Property 'name' don't exists on task 'PublishBuildArtifacts' anymore

### ISSUE THREAD

**Issue by lucimarckjsdias** [MicrosoftDocs/azure-docs.pt-br#566]
Please, update it with 'ArtifactName' in all samples.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 0ab62930-d35d-d6d3-8bb7-2ed6b34636bb
* Version Independent ID: 86725233-d4a5-a796-cd6e-c05c3675952b
* Content: [Fornecer atualizações de código de função continuamente usando o Azure DevOps-Azure Functions](https://docs.microsoft.com/pt-br/azure/azure-functions/functions-how-to-azure-devops?source=docs#feedback)
* Content Source: [articles/azure-functions/functions-how-to-azure-devops.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/azure-functions/functions-how-to-azure-devops.md)
* GitHub Login: @ahmedelnably
* Microsoft Alias: **aelnably**

**Comment by srvbpigh** [comment]
Hello, @lucimarckjsdias
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @lucimarckjsdias, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/45206. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
