### ISSUE TITLE
Clarification on local settings structure

### ISSUE THREAD

**Issue by mariomeyrelles** [MicrosoftDocs/azure-docs.pt-br#572]
I think the documentation should make clearer that the configurations needed for IOptions&lt;T&gt; should only be placed inside Values section of local.settings.json.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5786402e-9d88-5de0-607a-1c2a143af006
* Version Independent ID: 15368d1c-b22e-7eb2-413f-cc0d41d2b909
* Content: [Usar injeção de dependência no .NET do Azure Functions](https://docs.microsoft.com/pt-br/azure/azure-functions/functions-dotnet-dependency-injection#feedback)
* Content Source: [articles/azure-functions/functions-dotnet-dependency-injection.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/azure-functions/functions-dotnet-dependency-injection.md)
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by srvbpigh** [comment]
Hello, @mariomeyrelles
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @mariomeyrelles, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/45869. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
