### ISSUE TITLE
Error AADSTS50076

### ISSUE THREAD

**Issue by martininvillia** [MicrosoftDocs/azure-docs.pt-br#576]
Is it possible to authenticate with the oauth 2.0 protocol with the grant_type password for a user with MFA enabled?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: ffdaa549-8f3b-75e0-9d27-a1a10417d86b
* Version Independent ID: aff533db-3ac6-5f9a-0134-812f7d488670
* Content: [O que é o Acesso Condicional no Azure Active Directory?](https://docs.microsoft.com/pt-br/azure/active-directory/conditional-access/overview#feedback)
* Content Source: [articles/active-directory/conditional-access/overview.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/active-directory/conditional-access/overview.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @martininvillia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47163](https://github.com/MicrosoftDocs/azure-docs/issues/47163) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @martininvillia, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47163. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
