### ISSUE TITLE
Erro na seleção do tamanho de disco

### ISSUE THREAD

**Issue by josefelipearaujo** [MicrosoftDocs/azure-docs.pt-br#586]
Estou tentando seguir estas instruções porém não está sendo possível selecionar um tamanho de disco. Todas as alternativas da lista de seleção estão inválidas. Não é mais possível selecionar nenhuma delas.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2e58109c-c8d3-6693-8e1d-03a89ca26168
* Version Independent ID: f20a7fc4-328a-e90d-29db-92a91aa1b2bd
* Content: [Início Rápido – Criar uma VM Windows no portal do Azure](https://docs.microsoft.com/pt-br/azure/virtual-machines/windows/quick-create-portal#feedback)
* Content Source: [articles/virtual-machines/windows/quick-create-portal.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/virtual-machines/windows/quick-create-portal.md)
* Service: **virtual-machines-windows**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by srvbpigh** [comment]
Hello, @josefelipearaujo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #51318](https://github.com/MicrosoftDocs/azure-docs/issues/51318) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @josefelipearaujo, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/51318. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
