### ISSUE TITLE
Small correction

### ISSUE THREAD

**Issue by marcelo-salvatori** [MicrosoftDocs/azure-docs.pt-br#592]
"Scale up events" and "Scale down events" subtopics should be changed to "Scale out events" and "Scale in events", since there's no resource being added to existing nodes, but new nodes are being added.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9d8185fe-e724-7a2d-7579-8e94ef873b36
* Version Independent ID: 66dc644d-6edd-b5ad-d043-3ad4659e27b1
* Content: [Conceitos – dimensionar aplicativos no AKS (Serviço de Kubernetes do Azure)](https://docs.microsoft.com/pt-br/azure/aks/concepts-scale#feedback)
* Content Source: [articles/aks/concepts-scale.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/aks/concepts-scale.md)
* GitHub Login: @zr-msft
* Microsoft Alias: **zarhoads**

**Comment by srvbpigh** [comment]
Hello, @marcelo-salvatori
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52411](https://github.com/MicrosoftDocs/azure-docs/issues/52411) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @marcelo-salvatori, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/52411. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
