### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by gollima** [MicrosoftDocs/azure-docs.pt-br#595]
"datacenter public IP addresses" url on AzureCloud tag is pointing to the wrong place

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 08217244-82bb-13b5-46f7-454801d8f865
* Version Independent ID: 4a8b0a32-bf57-7544-c60d-6b7f250c4477
* Content: [Visão geral das tags de serviço do Azure](https://docs.microsoft.com/pt-br/azure/virtual-network/service-tags-overview#feedback)
* Content Source: [articles/virtual-network/service-tags-overview.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/virtual-network/service-tags-overview.md)
* Service: **virtual-network**
* GitHub Login: @jispar
* Microsoft Alias: **jispar**

**Comment by srvbpigh** [comment]
Hello, @gollima
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #53416](https://github.com/MicrosoftDocs/azure-docs/issues/53416) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @gollima, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/53416. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
