### ISSUE TITLE
See user's login

### ISSUE THREAD

**Issue by Brunolosse** [MicrosoftDocs/azure-docs.pt-br#599]
Is it possible to show the users Identification at the questions query?
I've tried user_AccountId, user_AuthenticatedId and user_Id but they return blank.
The channel I'm using is TEAMS.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 82bd07c0-ce21-9630-4aea-c93190c227fa
* Version Independent ID: f1912f4f-df33-edf2-9efe-3b7ae9e77876
* Content: [Análise na base de conhecimentos-QnA Maker - Azure Cognitive Services](https://docs.microsoft.com/pt-br/azure/cognitive-services/qnamaker/how-to/get-analytics-knowledge-base#feedback)
* Content Source: [articles/cognitive-services/QnAMaker/How-To/get-analytics-knowledge-base.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/cognitive-services/QnAMaker/How-To/get-analytics-knowledge-base.md)
* Service: **cognitive-services**
* Sub-service: **qna-maker**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by srvbpigh** [comment]
Hello, @Brunolosse
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #55616](https://github.com/MicrosoftDocs/azure-docs/issues/55616) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @Brunolosse, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/55616. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
